# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Data Tactics
tagline:          'A data blog'
description:      'A data science and programming blog'
url:              https://datatactics.ml
baseurl:          /

author:
  name:           'Eli Sakov'
  url:            https://datatactics.ml

paginate:         5

# Custom vars
version:          2.1.0

github:			https://github.com/Ely-S
connect:		https://www.linkedin.com/pub/eli-sakov/88/556/b65
contact: 		eli@datatactics.ml