# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Data + Code
tagline:          'A data blog'
description:      'An ML and programming blog'
url:              https://eli.cool/
baseurl:          /

author:
  name:           'Eli Sakov'
  url:            https://eli.cool/

paginate:         5

# Custom vars
version:          2.1.0

github:			https://github.com/Ely-S
connect:		https://www.linkedin.com/pub/eli-sakov/88/556/b65
email: 			eli.sakov@createthenext.com
resume: 		/resume.html